% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Aug-2017 12:47:28
%  MATLAB version: 9.2.0.556344 (R2017a)
% -------------------------------------------------------------------
saveVarsMat = load('ikiye_bolme_yontemi.mat');

F = saveVarsMat.F; % <1x1 inline> unsupported class

Fa = -2;

Fb = 3.4193953882637205;

Fxi = -0.00392609321674664;

a = 0.40625;

b = 0.408203125;

i = 10;

imax = 15;

tol = 0.001;

tole = 0.0009765625;

xi = 0.4072265625;

clear saveVarsMat;
